allowBuilds:
  core-js: true
  esbuild: true
  fsevents: true
  unrs-resolver: true

overrides:
  conventional-changelog-conventionalcommits: '>= 9.3.1'

publicHoistPattern:
  - '*prettier*'
  - styled-components
