allowBuilds:
  core-js: true
  esbuild: true
  fsevents: true
  unrs-resolver: true

overrides:
  conventional-changelog-conventionalcommits: '>= 10.2.0'

publicHoistPattern:
  - '*prettier*'
  - styled-components
